CREATE DATABASE QLBanhang;
USE QLBanhang;
CREATE TABLE KHACHHANG (
	MAKH NVARCHAR(5) PRIMARY KEY,
	TENKH NVARCHAR(30),
	DIACHI NVARCHAR(300),
	DT VARCHAR(10),
	EMAIL VARCHAR(30));
CREATE TABLE VATTU (
	MAVT NVARCHAR(5) PRIMARY KEY,
	TENVT NVARCHAR(30),
	DVT NVARCHAR(20),
	GIAMUA MONEY,
	SLTON INT);
CREATE TABLE HOADON (
	MAHD NVARCHAR(10) PRIMARY KEY,
	NGAY DATETIME,
	MAKH NVARCHAR(5),
	TONGTG MONEY);
CREATE TABLE CHITIETHOADON (
	MAHD NVARCHAR(10),
	MAVT NVARCHAR(5),
	SL INT,
	KHUYENMAI DECIMAL,
	GIABAN MONEY,
	PRIMARY KEY(MAHD, MAVT));
