--CAU 1--
USE QLBanhang;
GO
CREATE PROCEDURE SP_CAU1
AS
BEGIN
UPDATE HOADON
SET TONGTG = TONGIABAN
FROM HOADON H
JOIN (SELECT C.MAHD, SUM(C.GIABAN) AS TONGIABAN FROM CHITIETHOADON C GROUP BY C.MAHD) CT
ON H.MAHD = CT.MAHD;
END
GO
--CAU 2--
USE QLBanhang;
GO
CREATE PROCEDURE SP_CAU2 (@DT VARCHAR(10))
AS
BEGIN
IF EXISTS (SELECT * FROM KHACHHANG WHERE DT = @DT)
	BEGIN
	PRINT 'ĐÃ CÓ KHÁCH HÀNG CÓ SDT NÀY';
	END
ELSE
	BEGIN
	PRINT 'CHƯA CÓ KHÁCH HÀNG CÓ SDT NÀY';
	END
END
GO
--CAU 3--
USE QLBanhang;
GO
CREATE PROCEDURE SP_CAU3 (@MAKH NVARCHAR(5))
AS
BEGIN
RETURN (SELECT SUM(TONGTG) FROM HOADON WHERE MAKH = @MAKH)
END
GO
--CAU 4--
USE QLBanhang;
GO
CREATE PROCEDURE SP_CAU4 ( @MAVT NVARCHAR(5) OUTPUT, @TENVT NVARCHAR(30) OUTPUT)
AS
BEGIN
WITH RAW_DATA AS (
	SELECT MAVT , SUM(GIABAN * SL) AS TONGTIEN 
	FROM CHITIETHOADON 
	GROUP BY MAVT)
	SELECT @MAVT = R.MAVT
	FROM RAW_DATA R
	WHERE R.TONGTIEN = (SELECT MAX(TONGTIEN) FROM RAW_DATA);
	SELECT @TENVT = TENVT FROM VATTU WHERE MAVT = @MAVT;
END
GO

DECLARE @MA NVARCHAR(5); 
DECLARE @TEN NVARCHAR(30); 
EXECUTE SP_CAU4 @MA OUTPUT, @TEN OUTPUT;
SELECT @MA AS MAVT, @TEN AS TENVT;
SELECT * FROM CHITIETHOADON;

DECLARE @TOTAL AS MONEY;
EXECUTE @TOTAL = SP_CAU3 'KH01';
PRINT @TOTAL;


EXEC SP_CAU2 '09878987';
SELECT * FROM KHACHHANG;

BEGIN TRANSACTION
DELETE FROM CHITIETHOADON WHERE MAVT = 'VT01' AND MAHD = 'HD001';
UPDATE CHITIETHOADON SET GIABAN = 1000 WHERE MAVT = 'VT03' AND MAHD = 'HD002';
EXEC SP_CAU1;
SELECT * FROM HOADON
ROLLBACK TRANSACTION
SELECT * FROM HOADON