--CAU 1--
USE QLBanhang;
CREATE NONCLUSTERED INDEX IDX_VATTU_GIAMUA
ON VATTU (GIAMUA);
--CAU 2--
USE QLBanhang;
CREATE NONCLUSTERED INDEX IDX_VATTU_SLTON
ON VATTU (SLTON);
--CAU 3--
USE QLBanhang;
CREATE NONCLUSTERED INDEX IDX_HOADON_NGAY
ON HOADON (NGAY);