--CAU 1--
SELECT * FROM KHACHHANG;
--CAU 2--
SELECT * FROM KHACHHANG
WHERE DIACHI = 'TAN BINH'
ORDER BY MAKH;
--CAU 3--
SELECT * FROM KHACHHANG
WHERE DT IS NOT NULL AND EMAIL IS NOT NULL;
--CAU 4--
SELECT MAVT, TENVT, DVT, GIAMUA 
FROM VATTU;
--CAU 5--
SELECT MAVT, TENVT, DVT, GIAMUA 
FROM VATTU
WHERE GIAMUA BETWEEN 20000 AND 40000
ORDER BY GIAMUA DESC;
--CAU 6--
SELECT MAVT, TENVT, DVT, GIAMUA 
FROM VATTU
WHERE TENVT LIKE 'GACH%';
--CAU 7--
SELECT COUNT(MAVT) AS SLVT
FROM VATTU;
--CAU 8--
SELECT MAHD, COUNT(MAVT) AS SLVT
FROM CHITIETHOADON
GROUP BY MAHD;
-- CAU 9--
SELECT MAHD, SUM(GIABAN * SL) AS TONGTIEN
FROM CHITIETHOADON
GROUP BY MAHD;
--CAU 10--
SELECT MAKH, COUNT(MAHD) AS SLHD
FROM HOADON
GROUP BY MAKH;


