--CAU 1--
USE QLBanhang;
GO
CREATE FUNCTION FC_CAU1 (@MAVT NVARCHAR(5))
RETURNS INT
AS
BEGIN
RETURN (SELECT GIAMUA FROM VATTU WHERE MAVT = @MAVT);
END;
GO
--CAU 2--
USE QLBanhang;
GO
CREATE FUNCTION FC_CAU2 (@MAKH NVARCHAR(5))
RETURNS NVARCHAR(30)
AS 
BEGIN
RETURN (SELECT TENKH FROM KHACHHANG WHERE MAKH = @MAKH);
END
GO
--CAU 3--
USE QLBanhang;
GO
CREATE FUNCTION FC_CAU3 (@MAKH NVARCHAR(5))
RETURNS INT
AS
BEGIN
RETURN (SELECT SUM(TONGTG) FROM HOADON WHERE MAKH = @MAKH);
END
GO
--CAU 4--
USE QLBanhang;
GO
CREATE FUNCTION FC_CAU4()
RETURNS NVARCHAR(5)
AS 
BEGIN
RETURN (SELECT RW.MAVT
		FROM (
			SELECT MAVT, SUM(SL * GIABAN) AS TONGTIEN
			FROM CHITIETHOADON
			GROUP BY MAVT) RW
		WHERE RW.TONGTIEN IN (
			SELECT MAX(R.TONGTIEN)
			FROM (
				SELECT MAVT, SUM(SL * GIABAN) AS TONGTIEN
				FROM CHITIETHOADON
				GROUP BY MAVT) R)); 
END;
GO

SELECT DBO.FC_CAU1 ('VT03') GIAMUA;
SELECT DBO.FC_CAU2 ('KH01') TENKH;
SELECT DBO.FC_CAU3 ('KH01') TONGTIEN;
SELECT DBO.FC_CAU4 () MAVT;
