--CAU 1--
USE QLBanhang;
BEGIN TRANSACTION
INSERT INTO HOADON (MAHD, NGAY, MAKH)
	OUTPUT inserted.*
	VALUES ('HD20', '20191202', 'KH01');
INSERT INTO CHITIETHOADON (MAHD, MAVT, SL, GIABAN) 
	OUTPUT inserted.*
	VALUES 
	('HD20', 'VT01', 10, 55000),
	('HD20', 'VT02', 2, 47000);
ROLLBACK TRANSACTION
--CAU 2--
USE QLBanhang;
BEGIN TRANSACTION
DELETE FROM CHITIETHOADON
OUTPUT deleted.*
WHERE MAHD = 'HD008';

DELETE FROM HOADON
OUTPUT deleted.*
WHERE MAHD = 'HD008';
ROLLBACK TRANSACTION