USE QLBanhang;
--CAU 1--
SELECT *
FROM KHACHHANG
WHERE DT = '08457895';
--CAU 2--
SELECT MAVT, TENVT, DVT, GIAMUA
FROM VATTU
WHERE TENVT LIKE 'DA%' AND GIAMUA < 30000;
--CAU 3--
SELECT H.MAHD, H.NGAY, K.TENKH, K.DIACHI, K.DT
FROM HOADON H
JOIN KHACHHANG K
ON H.MAKH = K.MAKH
ORDER BY H.NGAY DESC;
--CAU 4--
SELECT K.TENKH, K.DIACHI, K.DT
FROM KHACHHANG K
WHERE K.MAKH IN (
	SELECT MAKH FROM HOADON WHERE NGAY BETWEEN '20000601' AND '20000630');
--CAU 5--
WITH TRIGIABAN AS (
	SELECT C.MAHD, C.MAVT, (SELECT V1.TENVT FROM VATTU V1 WHERE V1.MAVT = C.MAVT) AS TENVT, 
	(SELECT V2.GIAMUA FROM VATTU V2 WHERE V2.MAVT = C.MAVT) AS GIAMUA, C.SL, C.GIABAN, (C.GIABAN * C.SL) AS TRIGIABAN
	FROM CHITIETHOADON C),
	TRIGIAMUABAN AS (
	SELECT T.MAHD, T.MAVT, T.TENVT, T.GIABAN, T.GIAMUA, T.SL, (T.GIAMUA * T.SL) AS TRIGIAMUA, T.TRIGIABAN
	FROM TRIGIABAN T
	WHERE T.GIABAN >= T.GIAMUA)
	SELECT MB.MAHD, MB.MAVT, MB.TENVT, MB.GIABAN, MB.GIAMUA, 
		MB.SL, MB.TRIGIAMUA, MB.TRIGIABAN , (MB.TRIGIABAN - MB.TRIGIAMUA) AS TIENLOI
	FROM TRIGIAMUABAN MB;
--CAU 6--
SELECT TOP 1 H.MAHD, H.NGAY, K.MAKH, K.TENKH, K.DIACHI, H.TONGTG
FROM HOADON H
JOIN KHACHHANG K
ON H.MAKH = K.MAKH
WHERE H.NGAY BETWEEN '20000101' AND '20001231'
ORDER BY H.TONGTG;
--CAU 7--
WITH SOVATTU AS (
	SELECT MAHD, COUNT(MAVT) AS SVT
	FROM CHITIETHOADON
	GROUP BY MAHD)
	SELECT *
	FROM KHACHHANG K
	WHERE K.MAKH IN (
		SELECT H.MAKH 
		FROM HOADON H 
		JOIN SOVATTU S
		ON H.MAHD = S.MAHD
		WHERE S.SVT = (SELECT MIN(SVT.SVT) FROM SOVATTU SVT));
--CAU 8--
SELECT *
FROM VATTU
WHERE GIAMUA = (SELECT MIN(GIAMUA) FROM VATTU);
--CAU 9--
WITH RAW_DATA AS (
	SELECT C.MAHD, C.MAVT, C.GIABAN, H.NGAY
	FROM CHITIETHOADON C
	JOIN HOADON H
	ON C.MAHD = H.MAHD
	WHERE H.NGAY BETWEEN '20000101' AND '20001231')
	SELECT * 
	FROM VATTU
	WHERE MAVT = (
		SELECT TOP 1 R.MAVT 
		FROM RAW_DATA R 
		ORDER BY GIABAN DESC);


